[versions]
minecraft     = "26.2"
fabric-loader = "0.19.3"
fabric-api    = "0.152.1+26.2"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
mod-menu      = "20.0.0-beta.2"
keybinds      = "0.5.0+26.2"
yacl          = "3.9.4+26.2-fabric"

# Scripting
arcade        = "0.10.0-beta.4+26.2"

# Plugins
fabric-loom   = "1.17-SNAPSHOT"
mod-publish   = "0.8.1"
shadow        = "8.3.5"

[libraries]
minecraft     = { module = "com.mojang:minecraft"                    , version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader"              , version.ref = "fabric-loader" }
fabric-api    = { module = "net.fabricmc.fabric-api:fabric-api"      , version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin"     , version.ref = "fabric-kotlin" }
mod-menu      = { module = "com.terraformersmc:modmenu"              , version.ref = "mod-menu" }
keybinds      = { module = "me.senseiwells:simple-keybinding-library", version.ref = "keybinds" }
yacl          = { module = "dev.isxander:yet-another-config-lib"     , version.ref = "yacl" }

# Scripting
kotlin-metadata      = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm" }

arcade-commands       = { module = "net.casualchampionships:arcade-commands"      , version.ref = "arcade" }
arcade-event-registry = { module = "net.casualchampionships:arcade-event-registry", version.ref = "arcade" }
arcade-events-client  = { module = "net.casualchampionships:arcade-events-client" , version.ref = "arcade" }
arcade-events-server  = { module = "net.casualchampionships:arcade-events-server" , version.ref = "arcade" }
arcade-utils          = { module = "net.casualchampionships:arcade-utils"         , version.ref = "arcade" }

[bundles]
arcade = ["arcade-commands", "arcade-event-registry", "arcade-events-server", "arcade-events-client", "arcade-utils"]

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom"       , version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
shadow      = { id = "com.gradleup.shadow"            , version.ref = "shadow" }
